package by.epamtc.jwd.auth.model.ajax_entity;

public final class AjaxCommandName {

    public static final String FETCH_COUNTRY_IN_CHANGE_PATIENT_INFO_JSP
            = "FETCH-COUNTRY-IN-CHANGE-PATIENT-INFO-JSP";
    public static final String FETCH_REGION_IN_CHANGE_PATIENT_INFO_JSP
            = "FETCH-REGION-IN-CHANGE-PATIENT-INFO-JSP";
    public static final String FETCH_AREA_IN_CHANGE_PATIENT_INFO_JSP
            = "FETCH-AREA-IN-CHANGE-PATIENT-INFO-JSP";
    public static final String FETCH_SETTLEMENT_IN_CHANGE_PATIENT_INFO_JSP
            = "FETCH-SETTLEMENT-IN-CHANGE-PATIENT-INFO-JSP";
    public static final String FETCH_ROAD_IN_CHANGE_PATIENT_INFO_JSP
            = "FETCH-ROAD-IN-CHANGE-PATIENT-INFO-JSP";
    public static final String FETCH_PERSON_IN_MEDICAL_HISTORY_PERMISSION_JSP
            = "FETCH-PERSONS-IN-MEDICAL-HISTORY-PERMISSION-JSP";
    public static final String FETCH_FOOD_ALLERGY_IN_ALLERGIC_REACTIONS_JSP
            = "FETCH-FOOD-ALLERGY-IN-ALLERGIC-REACTIONS-JSP";
    public static final String FETCH_MEDICINE_ALLERGY_IN_ALLERGIC_REACTIONS_JSP
            = "FETCH-MEDICINE-ALLERGY-IN-ALLERGIC-REACTIONS-JSP";
    public static final String
            FETCH_EXTREMELY_HAZARDOUS_DISEASES_IN_EXTREMELY_HAZARDOUS_DISEASES_JSP
            = "FETCH-EXTREMELY-HAZARDOUS-DISEASES-IN-EXTREMELY-HAZARDOUS-" +
            "DISEASES-JSP";
    public static final String FETCH_PERSON_IN_REGISTER_VISIT_JSP
            = "FETCH-PERSONS-IN-REGISTER-VISIT-JSP";
    public static final String FETCH_DISEASES_IN_ESTABLISH_DIAGNOSIS_JSP
            = "FETCH-DISEASES-IN-ESTABLISH-DIAGNOSIS-JSP";
    public static final String FETCH_MEDICINES_IN_ESTABLISH_MEDICINE_PRESCRIPTION_JSP
            = "FETCH-MEDICINES-IN-ESTABLISH-MEDICINE_PRESCRIPTION-JSP";
    public static final String FETCH_PAGE_QUANTITY_IN_REFUSAL_REFERENCES_JSP
            = "FETCH-PAGE-QUANTITY-IN-REFUSAL-REFERENCES-JSP";
    public static final String FETCH_PAGE_QUANTITY_IN_REFUSAL_REFERENCES_FOR_PATIENT_JSP
            = "FETCH-PAGE-QUANTITY-IN-REFUSAL-REFERENCES-FOR-PATIENT-JSP";


    private AjaxCommandName() {
    }
}
